### ISSUE TITLE
Cannot use tag_edit with QGridLayout 

### ISSUE THREAD

**Issue by vale46n1** [ByteDream/PyQt5-expansion#1]
I tried to used it but I got this error:
AttributeError: 'QGridLayout' object has no attribute 'tag_edit'

How I can use it with a QGridLayout widget?
Thanks

**Comment by bytedream** [comment]
Could you send the (part of the) code where you trying to use it?

**Comment by vale46n1** [comment]
uic.loadUi('user.ui', self)
self.setFixedSize(958, 762)
....
self.widget = QTagEdit()       
self.widget.setTags(['A', 'B'])

widget is a QWidget made in QT Creator.

**Comment by bytedream** [comment]
You may have to specify the `parent` widget when creating the `QTagEdit`:
```python
...
self.widget = QTagEdit(parent=self)
self.widget.setTags(['A', 'B'])
...
```

**Comment by vale46n1** [comment]
Perfect. It is now displayed in the widget.
But it doesn't fit the size of the QWidget box.

![image](https://user-images.githubusercontent.com/36825789/168377064-12998084-bb98-4dc6-8cdd-b9db53e4b60f.png)

How can I solve?

**Comment by bytedream** [comment]
`QTagEdit` inherits `QtWidgets.QScrollArea` so you can look how to horizontal fit a `QScrollArea`.

It *may* work if you wrap it in a hbox. I haven't worked with pyqt since 1+ year so I do not remember exactly how the framework works.
